### ISSUE TITLE
improve MongoDB Java driver connection failures

### ISSUE THREAD

**Issue by scottmarlow** [jboss/jboss-nosql#1]
Attempting to connect to a local MongoDB server (host=localhost, port=3444) that is not running, gives continuous warnings logged:
"
10:35:27,452 WARNING [com.mongodb.DynamicConnectionStatus](pool-2-thread-1) Server seen down: localhost/127.0.0.1:3444 - java.io.IOException - message: couldn't connect to [localhost/127.0.0.1:3444] bc:java.net.ConnectException: Connection refused
10:35:27,463 WARNING [com.mongodb.DynamicConnectionStatus](pool-2-thread-1) Server seen down: localhost/127.0.0.1:3444 - java.io.IOException - message: couldn't connect to [localhost/127.0.0.1:3444] bc:java.net.ConnectException: Connection refused
".

Exception call stack related is:

"pool-2-thread-1@7461" prio=5 tid=0x78 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
      - locked <0x1d28> (a java.net.SocksSocketImpl)
      at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
      at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
      at java.net.Socket.connect(Socket.java:589)
      at com.mongodb.DBPort._open(DBPort.java:204)
      at com.mongodb.DBPort.go(DBPort.java:107)
      - locked <0x1d2c> (a com.mongodb.DBPort)
      at com.mongodb.DBPort.go(DBPort.java:88)
      at com.mongodb.DBPort.findOne(DBPort.java:143)
      at com.mongodb.DBPort.runCommand(DBPort.java:148)
      at com.mongodb.ConnectionStatus$UpdatableNode.update(ConnectionStatus.java:184)
      at com.mongodb.DynamicConnectionStatus$DynamicNode.update(DynamicConnectionStatus.java:167)
      at com.mongodb.DynamicConnectionStatus$1.run(DynamicConnectionStatus.java:114)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)

The configuration profile (work in progress still) is:

``` xml
<subsystem xmlns="urn:jboss:domain:mongodb:1.0">
            <profiles name="profiles" >
                <profile name="nosqltest" profile-name="nosqltestprofile" jndi-name="java:jboss/nosql/example" host-name="localhost" host-port="3444"/>
            </profiles>
</subsystem>
```

**Comment by scottmarlow** [comment]
I'm not sure what we should do differently yet but starting the application server and seeing repeated "Server seen down" warnings filling the server log is not good. 

Related is what to do when the MongoDB server goes down while applications are using it.  

Some related reference links:
http://blog.mongolab.com/2013/11/deep-dive-into-connection-pooling (deep dive into connection pooling) and http://docs.mongolab.com/connecting
